// Auto-generated by build.js — do not edit by hand.
// Re-run "node build.js" any time you add, remove, or rename images in /assets.
window.SITE_DATA = {
  "generatedAt": "2026-10-06T16:31:49.161Z",
  "logo": "assets/logo.png",
  "projects": [
    {
      "slug": "pepete",
      "title": "Pepete",
      "description": [
        "Pepete is an artisanal modern bakery and neighborhood cafe in Cairo, celebrated for signature flaky croissants, buttery morning viennoiserie, and handcrafted specialty coffees. Driven by an energetic young founder with an infectious love for warm hospitality, the bakery quickly built a dedicated following of regulars who appreciate authentic European baking methods delivered without any corporate pretension or dull minimalism.",
        "The strategic goal was creating a memorable brand personality that reflected the founder's bold, spirited character rather than blending into generic coffeehouse aesthetics. Pepete was conceived as a vibrant neighborhood sanctuary, a playful corner where serious pastry craft meets an upbeat, genuinely welcoming environment that feels instantly memorable, unapologetically genuine, and deeply fun."
      ],
      "direction": [
        "The identity is built to express the brand's freedom. Instead of settling into one visual lane, Pepete borrows the owner's confidence to set its own rules: loud, joyful, a little chaotic in the best way. The goal was to capture that first time through the door feeling, pure and almost childlike, the kind of joy that doesn't ask permission to exist.",
        "The wide, unrestrained color palette is intentional. Pepete isn't directed at a certain type of customer, it's purely neutral, which was extremely challenging when designing the brand's identity, though it was ultimately what made it fun.",
        "As for their slogan and voice? They have all the stuff. What can I say?"
      ],
      "order": 0,
      "cover": {
        "src": "assets/Pepete/1L.webp",
        "thumb": "assets/thumbs/Pepete/1L.webp",
        "video": false
      },
      "gallery": [
        {
          "src": "assets/Pepete/1L.webp",
          "thumb": "assets/thumbs/Pepete/1L.webp",
          "video": false
        },
        {
          "src": "assets/Pepete/2s L.mp4",
          "thumb": "assets/Pepete/2s L.mp4",
          "video": true
        },
        {
          "src": "assets/Pepete/2s R.webp",
          "thumb": "assets/thumbs/Pepete/2s R.webp",
          "video": false
        },
        {
          "src": "assets/Pepete/3L.webp",
          "thumb": "assets/thumbs/Pepete/3L.webp",
          "video": false
        },
        {
          "src": "assets/Pepete/4sL.webp",
          "thumb": "assets/thumbs/Pepete/4sL.webp",
          "video": false
        },
        {
          "src": "assets/Pepete/4s R.webp",
          "thumb": "assets/thumbs/Pepete/4s R.webp",
          "video": false
        },
        {
          "src": "assets/Pepete/5L.webp",
          "thumb": "assets/thumbs/Pepete/5L.webp",
          "video": false
        },
        {
          "src": "assets/Pepete/6L.webp",
          "thumb": "assets/thumbs/Pepete/6L.webp",
          "video": false
        },
        {
          "src": "assets/Pepete/7L.webp",
          "thumb": "assets/thumbs/Pepete/7L.webp",
          "video": false
        },
        {
          "src": "assets/Pepete/8L.webp",
          "thumb": "assets/thumbs/Pepete/8L.webp",
          "video": false
        },
        {
          "src": "assets/Pepete/9s L.gif",
          "thumb": "assets/Pepete/9s L.gif",
          "video": false
        },
        {
          "src": "assets/Pepete/9s R.png",
          "thumb": "assets/Pepete/9s R.png",
          "video": false
        },
        {
          "src": "assets/Pepete/10s L.webp",
          "thumb": "assets/thumbs/Pepete/10s L.webp",
          "video": false
        },
        {
          "src": "assets/Pepete/10s R.webp",
          "thumb": "assets/thumbs/Pepete/10s R.webp",
          "video": false
        },
        {
          "src": "assets/Pepete/11L.webp",
          "thumb": "assets/thumbs/Pepete/11L.webp",
          "video": false
        },
        {
          "src": "assets/Pepete/12L.png",
          "thumb": "assets/Pepete/12L.png",
          "video": false
        },
        {
          "src": "assets/Pepete/13s L.webp",
          "thumb": "assets/thumbs/Pepete/13s L.webp",
          "video": false
        },
        {
          "src": "assets/Pepete/13s R.gif",
          "thumb": "assets/Pepete/13s R.gif",
          "video": false
        },
        {
          "src": "assets/Pepete/14L.png",
          "thumb": "assets/Pepete/14L.png",
          "video": false
        },
        {
          "src": "assets/Pepete/15L.png",
          "thumb": "assets/Pepete/15L.png",
          "video": false
        },
        {
          "src": "assets/Pepete/16L.png",
          "thumb": "assets/Pepete/16L.png",
          "video": false
        },
        {
          "src": "assets/Pepete/17L.png",
          "thumb": "assets/Pepete/17L.png",
          "video": false
        }
      ],
      "rows": [
        {
          "type": "large",
          "src": "assets/Pepete/1L.webp",
          "thumb": "assets/thumbs/Pepete/1L.webp",
          "video": false
        },
        {
          "type": "pair",
          "left": "assets/Pepete/2s L.mp4",
          "leftThumb": "assets/Pepete/2s L.mp4",
          "leftVideo": true,
          "right": "assets/Pepete/2s R.webp",
          "rightThumb": "assets/thumbs/Pepete/2s R.webp",
          "rightVideo": false
        },
        {
          "type": "large",
          "src": "assets/Pepete/3L.webp",
          "thumb": "assets/thumbs/Pepete/3L.webp",
          "video": false
        },
        {
          "type": "pair",
          "left": "assets/Pepete/4sL.webp",
          "leftThumb": "assets/thumbs/Pepete/4sL.webp",
          "leftVideo": false,
          "right": "assets/Pepete/4s R.webp",
          "rightThumb": "assets/thumbs/Pepete/4s R.webp",
          "rightVideo": false
        },
        {
          "type": "large",
          "src": "assets/Pepete/5L.webp",
          "thumb": "assets/thumbs/Pepete/5L.webp",
          "video": false
        },
        {
          "type": "large",
          "src": "assets/Pepete/6L.webp",
          "thumb": "assets/thumbs/Pepete/6L.webp",
          "video": false
        },
        {
          "type": "large",
          "src": "assets/Pepete/7L.webp",
          "thumb": "assets/thumbs/Pepete/7L.webp",
          "video": false
        },
        {
          "type": "large",
          "src": "assets/Pepete/8L.webp",
          "thumb": "assets/thumbs/Pepete/8L.webp",
          "video": false
        },
        {
          "type": "pair",
          "left": "assets/Pepete/9s L.gif",
          "leftThumb": "assets/Pepete/9s L.gif",
          "leftVideo": false,
          "right": "assets/Pepete/9s R.png",
          "rightThumb": "assets/Pepete/9s R.png",
          "rightVideo": false
        },
        {
          "type": "pair",
          "left": "assets/Pepete/10s L.webp",
          "leftThumb": "assets/thumbs/Pepete/10s L.webp",
          "leftVideo": false,
          "right": "assets/Pepete/10s R.webp",
          "rightThumb": "assets/thumbs/Pepete/10s R.webp",
          "rightVideo": false
        },
        {
          "type": "large",
          "src": "assets/Pepete/11L.webp",
          "thumb": "assets/thumbs/Pepete/11L.webp",
          "video": false
        },
        {
          "type": "large",
          "src": "assets/Pepete/12L.png",
          "thumb": "assets/Pepete/12L.png",
          "video": false
        },
        {
          "type": "pair",
          "left": "assets/Pepete/13s L.webp",
          "leftThumb": "assets/thumbs/Pepete/13s L.webp",
          "leftVideo": false,
          "right": "assets/Pepete/13s R.gif",
          "rightThumb": "assets/Pepete/13s R.gif",
          "rightVideo": false
        },
        {
          "type": "large",
          "src": "assets/Pepete/14L.png",
          "thumb": "assets/Pepete/14L.png",
          "video": false
        },
        {
          "type": "large",
          "src": "assets/Pepete/15L.png",
          "thumb": "assets/Pepete/15L.png",
          "video": false
        },
        {
          "type": "large",
          "src": "assets/Pepete/16L.png",
          "thumb": "assets/Pepete/16L.png",
          "video": false
        },
        {
          "type": "large",
          "src": "assets/Pepete/17L.png",
          "thumb": "assets/Pepete/17L.png",
          "video": false
        }
      ]
    },
    {
      "slug": "era",
      "title": "Era",
      "description": [
        "Era is a forward-thinking real estate investment and corporate brokerage based in New Cairo. The company was founded to carve out a distinct footprint in an aggressive and crowded property market, delivering institutional advisory, portfolio curation, and strategic acquisitions for serious institutional investors seeking high-value development opportunities. Rather than blending into the repetitive sales noise typical of local real estate agencies, Era was conceived as an authoritative corporate powerhouse.",
        "The company needed a market presence that projected unyielding stability, transparency, and architectural permanence. In a rapidly rising urban landscape where commercial promises often outpace tangible reality, Era distinguishes itself by championing verifiable reliability, modern investment intelligence, and rigorous property advisory for institutional clients building lasting generational wealth across the Egyptian capital."
      ],
      "direction": [
        "The identity is constructed, literally. The logo reads like a block of buildings: sharp, structural, load bearing. Every angle between the letterforms is deliberate, cut with the same precision you'd expect from architecture, not typography. That geometric confidence is the whole message, as if the logo, and the brand, are built on solid ground.",
        "The color carries the same tone. Bold red against pitch black doesn't ask to be liked, it commands attention, the way a skyline does at night. Paired with the campaign line, \"A Brand New Era,\" the identity positions itself exactly where the name says: not an evolution of something old, but a new standard altogether, fitting for a market like New Cairo that's still actively being built."
      ],
      "order": 1,
      "cover": {
        "src": "assets/Era/1L.webp",
        "thumb": "assets/thumbs/Era/1L.webp",
        "video": false
      },
      "gallery": [
        {
          "src": "assets/Era/1L.webp",
          "thumb": "assets/thumbs/Era/1L.webp",
          "video": false
        },
        {
          "src": "assets/Era/2L.webp",
          "thumb": "assets/thumbs/Era/2L.webp",
          "video": false
        },
        {
          "src": "assets/Era/3L.webp",
          "thumb": "assets/thumbs/Era/3L.webp",
          "video": false
        },
        {
          "src": "assets/Era/4L.webp",
          "thumb": "assets/thumbs/Era/4L.webp",
          "video": false
        },
        {
          "src": "assets/Era/5s L.webp",
          "thumb": "assets/thumbs/Era/5s L.webp",
          "video": false
        },
        {
          "src": "assets/Era/5s R.webp",
          "thumb": "assets/thumbs/Era/5s R.webp",
          "video": false
        },
        {
          "src": "assets/Era/6s L.webp",
          "thumb": "assets/thumbs/Era/6s L.webp",
          "video": false
        },
        {
          "src": "assets/Era/6s R.webp",
          "thumb": "assets/thumbs/Era/6s R.webp",
          "video": false
        },
        {
          "src": "assets/Era/7L.webp",
          "thumb": "assets/thumbs/Era/7L.webp",
          "video": false
        }
      ],
      "rows": [
        {
          "type": "large",
          "src": "assets/Era/1L.webp",
          "thumb": "assets/thumbs/Era/1L.webp",
          "video": false
        },
        {
          "type": "large",
          "src": "assets/Era/2L.webp",
          "thumb": "assets/thumbs/Era/2L.webp",
          "video": false
        },
        {
          "type": "large",
          "src": "assets/Era/3L.webp",
          "thumb": "assets/thumbs/Era/3L.webp",
          "video": false
        },
        {
          "type": "large",
          "src": "assets/Era/4L.webp",
          "thumb": "assets/thumbs/Era/4L.webp",
          "video": false
        },
        {
          "type": "pair",
          "left": "assets/Era/5s L.webp",
          "leftThumb": "assets/thumbs/Era/5s L.webp",
          "leftVideo": false,
          "right": "assets/Era/5s R.webp",
          "rightThumb": "assets/thumbs/Era/5s R.webp",
          "rightVideo": false
        },
        {
          "type": "pair",
          "left": "assets/Era/6s L.webp",
          "leftThumb": "assets/thumbs/Era/6s L.webp",
          "leftVideo": false,
          "right": "assets/Era/6s R.webp",
          "rightThumb": "assets/thumbs/Era/6s R.webp",
          "rightVideo": false
        },
        {
          "type": "large",
          "src": "assets/Era/7L.webp",
          "thumb": "assets/thumbs/Era/7L.webp",
          "video": false
        }
      ]
    },
    {
      "slug": "buy-me-a-tea",
      "title": "Buy Me a Tea",
      "description": [
        "Buy Me a Tea, or شاي واحد in Arabic, is an Egyptian equivalent to the globally known Buy Me a Coffee platform. It provides a direct digital space where independent creators, freelance designers, artists, and writers can receive micro-donations and ongoing support from followers who appreciate their craft. In Egypt, coffee culture is popular, but sharing a hot glass of tea is the authentic daily ritual that binds people together across neighborhoods and creative studios.",
        "Creating an indigenous creator economy brand required translating tipping from an imported Western mechanism into a familiar, natural Egyptian expression of appreciation. Rather than presenting support as a cold transactional donation, the platform frames it as an invitation to pull up a chair, sit down together, and buy a friend a cup of tea. It celebrates everyday creative labor while making digital patron payments accessible, culturally relatable, and warmly community-centered."
      ],
      "direction": [
        "The direction here is a different language, but also a different culture. Freelancing is still a relatively new concept in Egypt, without the decades of familiarity it has elsewhere. A platform meant to serve that community had to feel young, loud, and alive, something that speaks directly to a generation figuring out this path for itself.",
        "That's why the identity leans fully into bold, dominant color and an illustrative, hand drawn hand. From the tea glass mark to the wordmark itself, everything is built by hand rather than through rigid grid systems, deliberately a little chaotic. That chaos does two things at once: it grabs a young audience's attention in a crowded feed, and more importantly, it resembles the freelance artist's craft itself, the whole thing feels like a handcrafted artboard. Which it actually is, the entire logo is fully hand drawn, just executed digitally."
      ],
      "order": 2,
      "cover": {
        "src": "assets/Buy me a tea/1L.webp",
        "thumb": "assets/thumbs/Buy me a tea/1L.webp",
        "video": false
      },
      "gallery": [
        {
          "src": "assets/Buy me a tea/1L.webp",
          "thumb": "assets/thumbs/Buy me a tea/1L.webp",
          "video": false
        },
        {
          "src": "assets/Buy me a tea/2l.webp",
          "thumb": "assets/thumbs/Buy me a tea/2l.webp",
          "video": false
        },
        {
          "src": "assets/Buy me a tea/3L.webp",
          "thumb": "assets/thumbs/Buy me a tea/3L.webp",
          "video": false
        },
        {
          "src": "assets/Buy me a tea/4L.webp",
          "thumb": "assets/thumbs/Buy me a tea/4L.webp",
          "video": false
        },
        {
          "src": "assets/Buy me a tea/5L.webp",
          "thumb": "assets/thumbs/Buy me a tea/5L.webp",
          "video": false
        },
        {
          "src": "assets/Buy me a tea/6S L.webp",
          "thumb": "assets/thumbs/Buy me a tea/6S L.webp",
          "video": false
        },
        {
          "src": "assets/Buy me a tea/6S R.webp",
          "thumb": "assets/thumbs/Buy me a tea/6S R.webp",
          "video": false
        },
        {
          "src": "assets/Buy me a tea/7s L.webp",
          "thumb": "assets/thumbs/Buy me a tea/7s L.webp",
          "video": false
        },
        {
          "src": "assets/Buy me a tea/7s R.webp",
          "thumb": "assets/thumbs/Buy me a tea/7s R.webp",
          "video": false
        },
        {
          "src": "assets/Buy me a tea/8s L.webp",
          "thumb": "assets/thumbs/Buy me a tea/8s L.webp",
          "video": false
        },
        {
          "src": "assets/Buy me a tea/8s R.webp",
          "thumb": "assets/thumbs/Buy me a tea/8s R.webp",
          "video": false
        },
        {
          "src": "assets/Buy me a tea/9L.webp",
          "thumb": "assets/thumbs/Buy me a tea/9L.webp",
          "video": false
        },
        {
          "src": "assets/Buy me a tea/10s L.webp",
          "thumb": "assets/thumbs/Buy me a tea/10s L.webp",
          "video": false
        },
        {
          "src": "assets/Buy me a tea/10s R.webp",
          "thumb": "assets/thumbs/Buy me a tea/10s R.webp",
          "video": false
        }
      ],
      "rows": [
        {
          "type": "large",
          "src": "assets/Buy me a tea/1L.webp",
          "thumb": "assets/thumbs/Buy me a tea/1L.webp",
          "video": false
        },
        {
          "type": "large",
          "src": "assets/Buy me a tea/2l.webp",
          "thumb": "assets/thumbs/Buy me a tea/2l.webp",
          "video": false
        },
        {
          "type": "large",
          "src": "assets/Buy me a tea/3L.webp",
          "thumb": "assets/thumbs/Buy me a tea/3L.webp",
          "video": false
        },
        {
          "type": "large",
          "src": "assets/Buy me a tea/4L.webp",
          "thumb": "assets/thumbs/Buy me a tea/4L.webp",
          "video": false
        },
        {
          "type": "large",
          "src": "assets/Buy me a tea/5L.webp",
          "thumb": "assets/thumbs/Buy me a tea/5L.webp",
          "video": false
        },
        {
          "type": "pair",
          "left": "assets/Buy me a tea/6S L.webp",
          "leftThumb": "assets/thumbs/Buy me a tea/6S L.webp",
          "leftVideo": false,
          "right": "assets/Buy me a tea/6S R.webp",
          "rightThumb": "assets/thumbs/Buy me a tea/6S R.webp",
          "rightVideo": false
        },
        {
          "type": "pair",
          "left": "assets/Buy me a tea/7s L.webp",
          "leftThumb": "assets/thumbs/Buy me a tea/7s L.webp",
          "leftVideo": false,
          "right": "assets/Buy me a tea/7s R.webp",
          "rightThumb": "assets/thumbs/Buy me a tea/7s R.webp",
          "rightVideo": false
        },
        {
          "type": "pair",
          "left": "assets/Buy me a tea/8s L.webp",
          "leftThumb": "assets/thumbs/Buy me a tea/8s L.webp",
          "leftVideo": false,
          "right": "assets/Buy me a tea/8s R.webp",
          "rightThumb": "assets/thumbs/Buy me a tea/8s R.webp",
          "rightVideo": false
        },
        {
          "type": "large",
          "src": "assets/Buy me a tea/9L.webp",
          "thumb": "assets/thumbs/Buy me a tea/9L.webp",
          "video": false
        },
        {
          "type": "pair",
          "left": "assets/Buy me a tea/10s L.webp",
          "leftThumb": "assets/thumbs/Buy me a tea/10s L.webp",
          "leftVideo": false,
          "right": "assets/Buy me a tea/10s R.webp",
          "rightThumb": "assets/thumbs/Buy me a tea/10s R.webp",
          "rightVideo": false
        }
      ]
    },
    {
      "slug": "",
      "title": "Alwaai Hayat",
      "description": [
        "Alwaai Hayat, which translates directly to \"Awareness is Life,\" is an Egyptian guidance and wellness organization providing dedicated life coaching, emotional counseling, and mindful family support. Founded to support individuals navigating profound personal transitions, newly formed marriages, and early parenthood, the initiative provides accessible workshops and one-on-one sessions designed to cultivate deep emotional resilience, inner grounding, and lasting relational harmony.",
        "Seeking emotional guidance can often feel intimidating, vulnerable, or socially stigmatized in traditional communities. Alwaai Hayat was established as a safe, compassionate haven that demystifies personal therapy, offering practical strategies to help individuals and couples overcome disorientation, cultivate genuine self-awareness, rebuild emotional clarity, and nurture healthy, enduring relationships throughout all life stages with dignity, warmth, and lasting inner peace."
      ],
      "direction": [
        "The identity is built with the same intention an NGO would carry: simple, multicolored, and strong. Nothing about it needed to be complicated, the message itself, awareness and renewal, had to come through at a glance.",
        "The logo is a modern depiction of a lotus flower, a symbol that in ancient Egypt represented rebirth and renewal, life beginning again after recreation. Drawn the way it is here, the lotus doubles as a rising sun, a more universal signal for a new day. The open, multi lined leaves carry a second meaning too, they read like open arms, welcoming and reassuring, which is exactly the feeling the brand wants someone to have the moment they consider reaching out for help."
      ],
      "order": 3,
      "cover": {
        "src": "assets/الوعي حياة/1L.webp",
        "thumb": "assets/thumbs/الوعي حياة/1L.webp",
        "video": false
      },
      "gallery": [
        {
          "src": "assets/الوعي حياة/1L.webp",
          "thumb": "assets/thumbs/الوعي حياة/1L.webp",
          "video": false
        },
        {
          "src": "assets/الوعي حياة/2L.webp",
          "thumb": "assets/thumbs/الوعي حياة/2L.webp",
          "video": false
        },
        {
          "src": "assets/الوعي حياة/3s L.webp",
          "thumb": "assets/thumbs/الوعي حياة/3s L.webp",
          "video": false
        },
        {
          "src": "assets/الوعي حياة/3s R.webp",
          "thumb": "assets/thumbs/الوعي حياة/3s R.webp",
          "video": false
        },
        {
          "src": "assets/الوعي حياة/4s L.webp",
          "thumb": "assets/thumbs/الوعي حياة/4s L.webp",
          "video": false
        },
        {
          "src": "assets/الوعي حياة/4s R.webp",
          "thumb": "assets/thumbs/الوعي حياة/4s R.webp",
          "video": false
        },
        {
          "src": "assets/الوعي حياة/5L.webp",
          "thumb": "assets/thumbs/الوعي حياة/5L.webp",
          "video": false
        },
        {
          "src": "assets/الوعي حياة/6L.webp",
          "thumb": "assets/thumbs/الوعي حياة/6L.webp",
          "video": false
        },
        {
          "src": "assets/الوعي حياة/7s L.webp",
          "thumb": "assets/thumbs/الوعي حياة/7s L.webp",
          "video": false
        },
        {
          "src": "assets/الوعي حياة/7s R.webp",
          "thumb": "assets/thumbs/الوعي حياة/7s R.webp",
          "video": false
        },
        {
          "src": "assets/الوعي حياة/8L.webp",
          "thumb": "assets/thumbs/الوعي حياة/8L.webp",
          "video": false
        },
        {
          "src": "assets/الوعي حياة/9L.webp",
          "thumb": "assets/thumbs/الوعي حياة/9L.webp",
          "video": false
        },
        {
          "src": "assets/الوعي حياة/10L.webp",
          "thumb": "assets/thumbs/الوعي حياة/10L.webp",
          "video": false
        },
        {
          "src": "assets/الوعي حياة/11s L.webp",
          "thumb": "assets/thumbs/الوعي حياة/11s L.webp",
          "video": false
        },
        {
          "src": "assets/الوعي حياة/11s R.webp",
          "thumb": "assets/thumbs/الوعي حياة/11s R.webp",
          "video": false
        }
      ],
      "rows": [
        {
          "type": "large",
          "src": "assets/الوعي حياة/1L.webp",
          "thumb": "assets/thumbs/الوعي حياة/1L.webp",
          "video": false
        },
        {
          "type": "large",
          "src": "assets/الوعي حياة/2L.webp",
          "thumb": "assets/thumbs/الوعي حياة/2L.webp",
          "video": false
        },
        {
          "type": "pair",
          "left": "assets/الوعي حياة/3s L.webp",
          "leftThumb": "assets/thumbs/الوعي حياة/3s L.webp",
          "leftVideo": false,
          "right": "assets/الوعي حياة/3s R.webp",
          "rightThumb": "assets/thumbs/الوعي حياة/3s R.webp",
          "rightVideo": false
        },
        {
          "type": "pair",
          "left": "assets/الوعي حياة/4s L.webp",
          "leftThumb": "assets/thumbs/الوعي حياة/4s L.webp",
          "leftVideo": false,
          "right": "assets/الوعي حياة/4s R.webp",
          "rightThumb": "assets/thumbs/الوعي حياة/4s R.webp",
          "rightVideo": false
        },
        {
          "type": "large",
          "src": "assets/الوعي حياة/5L.webp",
          "thumb": "assets/thumbs/الوعي حياة/5L.webp",
          "video": false
        },
        {
          "type": "large",
          "src": "assets/الوعي حياة/6L.webp",
          "thumb": "assets/thumbs/الوعي حياة/6L.webp",
          "video": false
        },
        {
          "type": "pair",
          "left": "assets/الوعي حياة/7s L.webp",
          "leftThumb": "assets/thumbs/الوعي حياة/7s L.webp",
          "leftVideo": false,
          "right": "assets/الوعي حياة/7s R.webp",
          "rightThumb": "assets/thumbs/الوعي حياة/7s R.webp",
          "rightVideo": false
        },
        {
          "type": "large",
          "src": "assets/الوعي حياة/8L.webp",
          "thumb": "assets/thumbs/الوعي حياة/8L.webp",
          "video": false
        },
        {
          "type": "large",
          "src": "assets/الوعي حياة/9L.webp",
          "thumb": "assets/thumbs/الوعي حياة/9L.webp",
          "video": false
        },
        {
          "type": "large",
          "src": "assets/الوعي حياة/10L.webp",
          "thumb": "assets/thumbs/الوعي حياة/10L.webp",
          "video": false
        },
        {
          "type": "pair",
          "left": "assets/الوعي حياة/11s L.webp",
          "leftThumb": "assets/thumbs/الوعي حياة/11s L.webp",
          "leftVideo": false,
          "right": "assets/الوعي حياة/11s R.webp",
          "rightThumb": "assets/thumbs/الوعي حياة/11s R.webp",
          "rightVideo": false
        }
      ]
    },
    {
      "slug": "juhayna-redesign",
      "title": "Juhayna",
      "description": [
        "Juhayna is Egypt's quintessential household food and beverage giant, celebrated since 1983 for continuously nourishing families across the nation through wholesome dairy products, fresh farm milks, rich yogurts, and natural juices. For over four decades, its vibrant four-petal flower emblem and heartfelt promise, Caring Everyday, have occupied a permanent place inside millions of breakfast tables and refrigerators nationwide, standing as a trusted generational symbol of authentic kitchen trust and reliable domestic comfort.",
        "Yet as contemporary visual culture evolves and supermarket aisles face unprecedented international competition, legacy Egyptian corporate market leaders must periodically revitalize their corporate presence without alienating their loyal customer base. The strategic brief behind this independent redesign concept was to elevate Juhayna's visual stature, infusing its classic packaging and diverse consumer touchpoints with refined modern elegance, organic freshness, and crisp shelf visibility across all major product categories.",
        "By honoring the deep emotional connection Egyptian consumers maintain with the heritage packaging, this concept preserves the indispensable brand markers while systematically resolving typographic tensions, color flatness, and structural stiffness. The result is a revitalized corporate identity that feels simultaneously reassuringly timeless and vibrantly modern, reaffirming Juhayna's unchallenged position as the country's most cherished everyday dairy and fruit juice provider."
      ],
      "direction": [
        "Rebranding requires a different skill set from building a brand from scratch. It's not just about improving a mark, it's about correctly identifying what actually needs to change, and just as importantly, what needs to stay exactly as it is.",
        "In Juhayna's case, the flower shape and its gradient are among the most recognizable marks in Egypt. Changing that wasn't an option, and this approach doesn't. Instead, a beam of light was introduced at the center of the flower, and the gradients themselves were reworked to feel more natural, less flat, and more alive, while staying unmistakably Juhayna.",
        "The typography took the same philosophy. The current wordmark is genuinely well made, the smiling يـ and y in both the English and Arabic is a lovely detail, but the letterforms themselves feel a little stiff, and the English and Arabic don't quite read as coming from the same type family. This approach closes that gap: both scripts now share the same closings and angles, and both carry a slight curve throughout, echoing the same smile that's already hidden in the يـ, just carried through the whole wordmark instead of a single letter, and in a more subtle, less literal way."
      ],
      "order": 4,
      "cover": {
        "src": "assets/Juhayna redesign/1s L.webp",
        "thumb": "assets/thumbs/Juhayna redesign/1s L.webp",
        "video": false
      },
      "gallery": [
        {
          "src": "assets/Juhayna redesign/1s L.webp",
          "thumb": "assets/thumbs/Juhayna redesign/1s L.webp",
          "video": false
        },
        {
          "src": "assets/Juhayna redesign/1s R.webp",
          "thumb": "assets/thumbs/Juhayna redesign/1s R.webp",
          "video": false
        },
        {
          "src": "assets/Juhayna redesign/2L.webp",
          "thumb": "assets/thumbs/Juhayna redesign/2L.webp",
          "video": false
        },
        {
          "src": "assets/Juhayna redesign/3 L.webp",
          "thumb": "assets/thumbs/Juhayna redesign/3 L.webp",
          "video": false
        },
        {
          "src": "assets/Juhayna redesign/4L.webp",
          "thumb": "assets/thumbs/Juhayna redesign/4L.webp",
          "video": false
        },
        {
          "src": "assets/Juhayna redesign/5L.webp",
          "thumb": "assets/thumbs/Juhayna redesign/5L.webp",
          "video": false
        },
        {
          "src": "assets/Juhayna redesign/6s L.webp",
          "thumb": "assets/thumbs/Juhayna redesign/6s L.webp",
          "video": false
        },
        {
          "src": "assets/Juhayna redesign/6s R.webp",
          "thumb": "assets/thumbs/Juhayna redesign/6s R.webp",
          "video": false
        },
        {
          "src": "assets/Juhayna redesign/7s L.webp",
          "thumb": "assets/thumbs/Juhayna redesign/7s L.webp",
          "video": false
        },
        {
          "src": "assets/Juhayna redesign/7s R.webp",
          "thumb": "assets/thumbs/Juhayna redesign/7s R.webp",
          "video": false
        },
        {
          "src": "assets/Juhayna redesign/8L.webp",
          "thumb": "assets/thumbs/Juhayna redesign/8L.webp",
          "video": false
        },
        {
          "src": "assets/Juhayna redesign/9L.webp",
          "thumb": "assets/thumbs/Juhayna redesign/9L.webp",
          "video": false
        },
        {
          "src": "assets/Juhayna redesign/10L.webp",
          "thumb": "assets/thumbs/Juhayna redesign/10L.webp",
          "video": false
        },
        {
          "src": "assets/Juhayna redesign/11s L.webp",
          "thumb": "assets/thumbs/Juhayna redesign/11s L.webp",
          "video": false
        },
        {
          "src": "assets/Juhayna redesign/11s R.webp",
          "thumb": "assets/thumbs/Juhayna redesign/11s R.webp",
          "video": false
        }
      ],
      "rows": [
        {
          "type": "pair",
          "left": "assets/Juhayna redesign/1s L.webp",
          "leftThumb": "assets/thumbs/Juhayna redesign/1s L.webp",
          "leftVideo": false,
          "right": "assets/Juhayna redesign/1s R.webp",
          "rightThumb": "assets/thumbs/Juhayna redesign/1s R.webp",
          "rightVideo": false
        },
        {
          "type": "large",
          "src": "assets/Juhayna redesign/2L.webp",
          "thumb": "assets/thumbs/Juhayna redesign/2L.webp",
          "video": false
        },
        {
          "type": "large",
          "src": "assets/Juhayna redesign/3 L.webp",
          "thumb": "assets/thumbs/Juhayna redesign/3 L.webp",
          "video": false
        },
        {
          "type": "large",
          "src": "assets/Juhayna redesign/4L.webp",
          "thumb": "assets/thumbs/Juhayna redesign/4L.webp",
          "video": false
        },
        {
          "type": "large",
          "src": "assets/Juhayna redesign/5L.webp",
          "thumb": "assets/thumbs/Juhayna redesign/5L.webp",
          "video": false
        },
        {
          "type": "pair",
          "left": "assets/Juhayna redesign/6s L.webp",
          "leftThumb": "assets/thumbs/Juhayna redesign/6s L.webp",
          "leftVideo": false,
          "right": "assets/Juhayna redesign/6s R.webp",
          "rightThumb": "assets/thumbs/Juhayna redesign/6s R.webp",
          "rightVideo": false
        },
        {
          "type": "pair",
          "left": "assets/Juhayna redesign/7s L.webp",
          "leftThumb": "assets/thumbs/Juhayna redesign/7s L.webp",
          "leftVideo": false,
          "right": "assets/Juhayna redesign/7s R.webp",
          "rightThumb": "assets/thumbs/Juhayna redesign/7s R.webp",
          "rightVideo": false
        },
        {
          "type": "large",
          "src": "assets/Juhayna redesign/8L.webp",
          "thumb": "assets/thumbs/Juhayna redesign/8L.webp",
          "video": false
        },
        {
          "type": "large",
          "src": "assets/Juhayna redesign/9L.webp",
          "thumb": "assets/thumbs/Juhayna redesign/9L.webp",
          "video": false
        },
        {
          "type": "large",
          "src": "assets/Juhayna redesign/10L.webp",
          "thumb": "assets/thumbs/Juhayna redesign/10L.webp",
          "video": false
        },
        {
          "type": "pair",
          "left": "assets/Juhayna redesign/11s L.webp",
          "leftThumb": "assets/thumbs/Juhayna redesign/11s L.webp",
          "leftVideo": false,
          "right": "assets/Juhayna redesign/11s R.webp",
          "rightThumb": "assets/thumbs/Juhayna redesign/11s R.webp",
          "rightVideo": false
        }
      ]
    },
    {
      "slug": "urban-oasis",
      "title": "Urban Oasis",
      "description": [
        "Urban Oasis is a visionary sustainable lifestyle brand conceived to reconnect city dwellers with living greenery through smart indoor hydroponics, architectural planters, and ecological home goods. As urban density increases and metropolitan apartments become increasingly detached from nature, the brand introduces accessible, low-maintenance biological systems that transform concrete living quarters into thriving, air-purifying domestic sanctuaries. It reimagines contemporary urban living by bringing clean sustainable agriculture and lush botanical foliage straight into residential interiors.",
        "The brand bridges the gap between high-efficiency automated cultivation technology and serene natural interior aesthetics, empowering city residents to grow fresh organic greens directly from their living room walls. By prioritizing recycled materials, closed-loop water conservation, and clean sculptural lines, Urban Oasis champions a mindful, eco-conscious philosophy tailored for modern architecture. It transforms everyday apartments into refreshing personal oases where humans, design, and vibrant botanical life coexist in complete harmony."
      ],
      "direction": [
        "Since Urban Oasis merges technology and ecology, the design language focuses on modern minimalism drawn from natural forms. The logo resembles a U shaped pot holding a pixel style palm tree, referencing the oasis itself. The mark is complex in concept yet simple in execution, which mirrors the brand's overall identity: the mix of simplicity, natural greenery, and neon color rendered in precise pixelated geometry is essentially what the brand is about.",
        "Look closer at the silhouette and there's a smile hidden in the U shaped pot, and open arms formed by the leaves. Both were the original spark, the first idea that came to mind when reading the brief. Everything else in the branding stays deliberately simple. Even the billboard is designed on transparent glass so the trees behind it show through, letting the idea show its work rather than explain itself."
      ],
      "order": 5,
      "cover": {
        "src": "assets/Urban Oasis/1L.webp",
        "thumb": "assets/thumbs/Urban Oasis/1L.webp",
        "video": false
      },
      "gallery": [
        {
          "src": "assets/Urban Oasis/1L.webp",
          "thumb": "assets/thumbs/Urban Oasis/1L.webp",
          "video": false
        },
        {
          "src": "assets/Urban Oasis/2L.webp",
          "thumb": "assets/thumbs/Urban Oasis/2L.webp",
          "video": false
        },
        {
          "src": "assets/Urban Oasis/3L.webp",
          "thumb": "assets/thumbs/Urban Oasis/3L.webp",
          "video": false
        },
        {
          "src": "assets/Urban Oasis/4L.webp",
          "thumb": "assets/thumbs/Urban Oasis/4L.webp",
          "video": false
        },
        {
          "src": "assets/Urban Oasis/5s L.webp",
          "thumb": "assets/thumbs/Urban Oasis/5s L.webp",
          "video": false
        },
        {
          "src": "assets/Urban Oasis/5s R.webp",
          "thumb": "assets/thumbs/Urban Oasis/5s R.webp",
          "video": false
        },
        {
          "src": "assets/Urban Oasis/6L.webp",
          "thumb": "assets/thumbs/Urban Oasis/6L.webp",
          "video": false
        },
        {
          "src": "assets/Urban Oasis/7s L.webp",
          "thumb": "assets/thumbs/Urban Oasis/7s L.webp",
          "video": false
        },
        {
          "src": "assets/Urban Oasis/7s R.webp",
          "thumb": "assets/thumbs/Urban Oasis/7s R.webp",
          "video": false
        },
        {
          "src": "assets/Urban Oasis/8L.webp",
          "thumb": "assets/thumbs/Urban Oasis/8L.webp",
          "video": false
        }
      ],
      "rows": [
        {
          "type": "large",
          "src": "assets/Urban Oasis/1L.webp",
          "thumb": "assets/thumbs/Urban Oasis/1L.webp",
          "video": false
        },
        {
          "type": "large",
          "src": "assets/Urban Oasis/2L.webp",
          "thumb": "assets/thumbs/Urban Oasis/2L.webp",
          "video": false
        },
        {
          "type": "large",
          "src": "assets/Urban Oasis/3L.webp",
          "thumb": "assets/thumbs/Urban Oasis/3L.webp",
          "video": false
        },
        {
          "type": "large",
          "src": "assets/Urban Oasis/4L.webp",
          "thumb": "assets/thumbs/Urban Oasis/4L.webp",
          "video": false
        },
        {
          "type": "pair",
          "left": "assets/Urban Oasis/5s L.webp",
          "leftThumb": "assets/thumbs/Urban Oasis/5s L.webp",
          "leftVideo": false,
          "right": "assets/Urban Oasis/5s R.webp",
          "rightThumb": "assets/thumbs/Urban Oasis/5s R.webp",
          "rightVideo": false
        },
        {
          "type": "large",
          "src": "assets/Urban Oasis/6L.webp",
          "thumb": "assets/thumbs/Urban Oasis/6L.webp",
          "video": false
        },
        {
          "type": "pair",
          "left": "assets/Urban Oasis/7s L.webp",
          "leftThumb": "assets/thumbs/Urban Oasis/7s L.webp",
          "leftVideo": false,
          "right": "assets/Urban Oasis/7s R.webp",
          "rightThumb": "assets/thumbs/Urban Oasis/7s R.webp",
          "rightVideo": false
        },
        {
          "type": "large",
          "src": "assets/Urban Oasis/8L.webp",
          "thumb": "assets/thumbs/Urban Oasis/8L.webp",
          "video": false
        }
      ]
    }
  ]
};
