// Auto-generated by build.js — do not edit by hand.
// Re-run "node build.js" any time you add, remove, or rename images in /assets.
window.SITE_DATA = {
  "generatedAt": "2026-10-02T21:00:02.699Z",
  "logo": "assets/logo.png",
  "projects": [
    {
      "slug": "buy-me-a-tea",
      "title": "Buy Me a Tea",
      "description": "Buy Me a Tea, or شاي واحد in Arabic, is an Egyptian made equivalent to the globally known Buy Me a Coffee, a platform where freelancers and creators can receive support and tips from the people who follow their work.",
      "direction": [
        "The direction here is a different language, but also a different culture. Freelancing is still a relatively new concept in Egypt, without the decades of familiarity it has elsewhere. A platform meant to serve that community had to feel young, loud, and alive, something that speaks directly to a generation figuring out this path for itself.",
        "That's why the identity leans fully into bold, dominant color and an illustrative, hand drawn hand. From the tea glass mark to the wordmark itself, everything is built by hand rather than through rigid grid systems, deliberately a little chaotic. That chaos does two things at once: it grabs a young audience's attention in a crowded feed, and more importantly, it resembles the freelance artist's craft itself, the whole thing feels like a handcrafted artboard. Which it actually is, the entire logo is fully hand drawn, just executed digitally."
      ],
      "order": 0,
      "cover": {
        "src": "assets/Buy me a tea/1L.webp",
        "video": false
      },
      "gallery": [
        {
          "src": "assets/Buy me a tea/1L.webp",
          "video": false
        },
        {
          "src": "assets/Buy me a tea/2l.webp",
          "video": false
        },
        {
          "src": "assets/Buy me a tea/3L.webp",
          "video": false
        },
        {
          "src": "assets/Buy me a tea/4L.webp",
          "video": false
        },
        {
          "src": "assets/Buy me a tea/5L.webp",
          "video": false
        },
        {
          "src": "assets/Buy me a tea/6S L.webp",
          "video": false
        },
        {
          "src": "assets/Buy me a tea/6S R.webp",
          "video": false
        },
        {
          "src": "assets/Buy me a tea/7s L.webp",
          "video": false
        },
        {
          "src": "assets/Buy me a tea/7s R.webp",
          "video": false
        },
        {
          "src": "assets/Buy me a tea/8s L.webp",
          "video": false
        },
        {
          "src": "assets/Buy me a tea/8s R.webp",
          "video": false
        },
        {
          "src": "assets/Buy me a tea/9L.webp",
          "video": false
        },
        {
          "src": "assets/Buy me a tea/10s L.webp",
          "video": false
        },
        {
          "src": "assets/Buy me a tea/10s R.webp",
          "video": false
        }
      ],
      "rows": [
        {
          "type": "large",
          "src": "assets/Buy me a tea/1L.webp",
          "video": false
        },
        {
          "type": "large",
          "src": "assets/Buy me a tea/2l.webp",
          "video": false
        },
        {
          "type": "large",
          "src": "assets/Buy me a tea/3L.webp",
          "video": false
        },
        {
          "type": "large",
          "src": "assets/Buy me a tea/4L.webp",
          "video": false
        },
        {
          "type": "large",
          "src": "assets/Buy me a tea/5L.webp",
          "video": false
        },
        {
          "type": "pair",
          "left": "assets/Buy me a tea/6S L.webp",
          "leftVideo": false,
          "right": "assets/Buy me a tea/6S R.webp",
          "rightVideo": false
        },
        {
          "type": "pair",
          "left": "assets/Buy me a tea/7s L.webp",
          "leftVideo": false,
          "right": "assets/Buy me a tea/7s R.webp",
          "rightVideo": false
        },
        {
          "type": "pair",
          "left": "assets/Buy me a tea/8s L.webp",
          "leftVideo": false,
          "right": "assets/Buy me a tea/8s R.webp",
          "rightVideo": false
        },
        {
          "type": "large",
          "src": "assets/Buy me a tea/9L.webp",
          "video": false
        },
        {
          "type": "pair",
          "left": "assets/Buy me a tea/10s L.webp",
          "leftVideo": false,
          "right": "assets/Buy me a tea/10s R.webp",
          "rightVideo": false
        }
      ]
    },
    {
      "slug": "era",
      "title": "Era",
      "description": "Era is a real estate investment and brokerage corporation operating in New Cairo, built as a genuinely new brand entering the market, one meant to set a new standard rather than follow the existing ones.",
      "direction": [
        "The identity is constructed, literally. The logo reads like a block of buildings: sharp, structural, load bearing. Every angle between the letterforms is deliberate, cut with the same precision you'd expect from architecture, not typography. That geometric confidence is the whole message, as if the logo, and the brand, are built on solid ground.",
        "The color carries the same tone. Bold red against pitch black doesn't ask to be liked, it commands attention, the way a skyline does at night. Paired with the campaign line, \"A Brand New Era,\" the identity positions itself exactly where the name says: not an evolution of something old, but a new standard altogether, fitting for a market like New Cairo that's still actively being built."
      ],
      "order": 0,
      "cover": {
        "src": "assets/Era/1L.webp",
        "video": false
      },
      "gallery": [
        {
          "src": "assets/Era/1L.webp",
          "video": false
        },
        {
          "src": "assets/Era/2L.webp",
          "video": false
        },
        {
          "src": "assets/Era/3L.webp",
          "video": false
        },
        {
          "src": "assets/Era/4L.webp",
          "video": false
        },
        {
          "src": "assets/Era/5s L.webp",
          "video": false
        },
        {
          "src": "assets/Era/5s R.webp",
          "video": false
        },
        {
          "src": "assets/Era/6s L.webp",
          "video": false
        },
        {
          "src": "assets/Era/6s R.webp",
          "video": false
        },
        {
          "src": "assets/Era/7L.webp",
          "video": false
        }
      ],
      "rows": [
        {
          "type": "large",
          "src": "assets/Era/1L.webp",
          "video": false
        },
        {
          "type": "large",
          "src": "assets/Era/2L.webp",
          "video": false
        },
        {
          "type": "large",
          "src": "assets/Era/3L.webp",
          "video": false
        },
        {
          "type": "large",
          "src": "assets/Era/4L.webp",
          "video": false
        },
        {
          "type": "pair",
          "left": "assets/Era/5s L.webp",
          "leftVideo": false,
          "right": "assets/Era/5s R.webp",
          "rightVideo": false
        },
        {
          "type": "pair",
          "left": "assets/Era/6s L.webp",
          "leftVideo": false,
          "right": "assets/Era/6s R.webp",
          "rightVideo": false
        },
        {
          "type": "large",
          "src": "assets/Era/7L.webp",
          "video": false
        }
      ]
    },
    {
      "slug": "juhayna-redesign",
      "title": "Juhayna",
      "description": "Juhayna is one of Egypt's most recognized dairy and juice brands, known since 1983 for its distinctive flower mark and the promise behind its tagline, Caring Everyday.",
      "direction": [
        "Rebranding requires a different skill set from building a brand from scratch. It's not just about improving a mark, it's about correctly identifying what actually needs to change, and just as importantly, what needs to stay exactly as it is.",
        "In Juhayna's case, the flower shape and its gradient are among the most recognizable marks in Egypt. Changing that wasn't an option, and this approach doesn't. Instead, a beam of light was introduced at the center of the flower, and the gradients themselves were reworked to feel more natural, less flat, and more alive, while staying unmistakably Juhayna.",
        "The typography took the same philosophy. The current wordmark is genuinely well made, the smiling يـ and y in both the English and Arabic is a lovely detail, but the letterforms themselves feel a little stiff, and the English and Arabic don't quite read as coming from the same type family. This approach closes that gap: both scripts now share the same closings and angles, and both carry a slight curve throughout, echoing the same smile that's already hidden in the يـ, just carried through the whole wordmark instead of a single letter, and in a more subtle, less literal way."
      ],
      "order": 0,
      "cover": {
        "src": "assets/Juhayna redesign/1s L.webp",
        "video": false
      },
      "gallery": [
        {
          "src": "assets/Juhayna redesign/1s L.webp",
          "video": false
        },
        {
          "src": "assets/Juhayna redesign/1s R.webp",
          "video": false
        },
        {
          "src": "assets/Juhayna redesign/2L.webp",
          "video": false
        },
        {
          "src": "assets/Juhayna redesign/3 L.webp",
          "video": false
        },
        {
          "src": "assets/Juhayna redesign/4L.webp",
          "video": false
        },
        {
          "src": "assets/Juhayna redesign/5L.webp",
          "video": false
        },
        {
          "src": "assets/Juhayna redesign/6s L.webp",
          "video": false
        },
        {
          "src": "assets/Juhayna redesign/6s R.webp",
          "video": false
        },
        {
          "src": "assets/Juhayna redesign/7s L.webp",
          "video": false
        },
        {
          "src": "assets/Juhayna redesign/7s R.webp",
          "video": false
        },
        {
          "src": "assets/Juhayna redesign/8L.webp",
          "video": false
        },
        {
          "src": "assets/Juhayna redesign/9L.webp",
          "video": false
        },
        {
          "src": "assets/Juhayna redesign/10L.webp",
          "video": false
        },
        {
          "src": "assets/Juhayna redesign/11s L.webp",
          "video": false
        },
        {
          "src": "assets/Juhayna redesign/11s R.webp",
          "video": false
        }
      ],
      "rows": [
        {
          "type": "pair",
          "left": "assets/Juhayna redesign/1s L.webp",
          "leftVideo": false,
          "right": "assets/Juhayna redesign/1s R.webp",
          "rightVideo": false
        },
        {
          "type": "large",
          "src": "assets/Juhayna redesign/2L.webp",
          "video": false
        },
        {
          "type": "large",
          "src": "assets/Juhayna redesign/3 L.webp",
          "video": false
        },
        {
          "type": "large",
          "src": "assets/Juhayna redesign/4L.webp",
          "video": false
        },
        {
          "type": "large",
          "src": "assets/Juhayna redesign/5L.webp",
          "video": false
        },
        {
          "type": "pair",
          "left": "assets/Juhayna redesign/6s L.webp",
          "leftVideo": false,
          "right": "assets/Juhayna redesign/6s R.webp",
          "rightVideo": false
        },
        {
          "type": "pair",
          "left": "assets/Juhayna redesign/7s L.webp",
          "leftVideo": false,
          "right": "assets/Juhayna redesign/7s R.webp",
          "rightVideo": false
        },
        {
          "type": "large",
          "src": "assets/Juhayna redesign/8L.webp",
          "video": false
        },
        {
          "type": "large",
          "src": "assets/Juhayna redesign/9L.webp",
          "video": false
        },
        {
          "type": "large",
          "src": "assets/Juhayna redesign/10L.webp",
          "video": false
        },
        {
          "type": "pair",
          "left": "assets/Juhayna redesign/11s L.webp",
          "leftVideo": false,
          "right": "assets/Juhayna redesign/11s R.webp",
          "rightVideo": false
        }
      ]
    },
    {
      "slug": "pepete",
      "title": "Pepete",
      "description": "Pepete is a small modern bakery and café, run by a young owner whose personality shows up in everything the brand touches: playful, a little cheeky, unapologetically herself. And yes, the croissants are excellent.",
      "direction": [
        "The identity is built to express the brand's freedom. Instead of settling into one visual lane, Pepete borrows the owner's confidence to set its own rules: loud, joyful, a little chaotic in the best way. The goal was to capture that first time through the door feeling, pure and almost childlike, the kind of joy that doesn't ask permission to exist.",
        "The wide, unrestrained color palette is intentional. Pepete isn't directed at a certain type of customer, it's purely neutral, which was extremely challenging when designing the brand's identity, though it was ultimately what made it fun.",
        "As for their slogan and voice? They have all the stuff. What can I say?"
      ],
      "order": 0,
      "cover": {
        "src": "assets/Pepete/1L.webp",
        "video": false
      },
      "gallery": [
        {
          "src": "assets/Pepete/1L.webp",
          "video": false
        },
        {
          "src": "assets/Pepete/2s L.mp4",
          "video": true
        },
        {
          "src": "assets/Pepete/2s R.webp",
          "video": false
        },
        {
          "src": "assets/Pepete/3L.webp",
          "video": false
        },
        {
          "src": "assets/Pepete/4sL.webp",
          "video": false
        },
        {
          "src": "assets/Pepete/4s R.webp",
          "video": false
        },
        {
          "src": "assets/Pepete/5L.webp",
          "video": false
        },
        {
          "src": "assets/Pepete/6L.webp",
          "video": false
        },
        {
          "src": "assets/Pepete/7L.webp",
          "video": false
        },
        {
          "src": "assets/Pepete/8L.webp",
          "video": false
        },
        {
          "src": "assets/Pepete/9s L.webp",
          "video": false
        },
        {
          "src": "assets/Pepete/9s R.webp",
          "video": false
        },
        {
          "src": "assets/Pepete/10s L.webp",
          "video": false
        },
        {
          "src": "assets/Pepete/10s R.webp",
          "video": false
        },
        {
          "src": "assets/Pepete/11L.webp",
          "video": false
        },
        {
          "src": "assets/Pepete/12L.webp",
          "video": false
        },
        {
          "src": "assets/Pepete/13s L.webp",
          "video": false
        },
        {
          "src": "assets/Pepete/13s R.webp",
          "video": false
        },
        {
          "src": "assets/Pepete/14L.webp",
          "video": false
        },
        {
          "src": "assets/Pepete/15L.webp",
          "video": false
        },
        {
          "src": "assets/Pepete/16L.webp",
          "video": false
        },
        {
          "src": "assets/Pepete/17L.webp",
          "video": false
        }
      ],
      "rows": [
        {
          "type": "large",
          "src": "assets/Pepete/1L.webp",
          "video": false
        },
        {
          "type": "pair",
          "left": "assets/Pepete/2s L.mp4",
          "leftVideo": true,
          "right": "assets/Pepete/2s R.webp",
          "rightVideo": false
        },
        {
          "type": "large",
          "src": "assets/Pepete/3L.webp",
          "video": false
        },
        {
          "type": "pair",
          "left": "assets/Pepete/4sL.webp",
          "leftVideo": false,
          "right": "assets/Pepete/4s R.webp",
          "rightVideo": false
        },
        {
          "type": "large",
          "src": "assets/Pepete/5L.webp",
          "video": false
        },
        {
          "type": "large",
          "src": "assets/Pepete/6L.webp",
          "video": false
        },
        {
          "type": "large",
          "src": "assets/Pepete/7L.webp",
          "video": false
        },
        {
          "type": "large",
          "src": "assets/Pepete/8L.webp",
          "video": false
        },
        {
          "type": "pair",
          "left": "assets/Pepete/9s L.webp",
          "leftVideo": false,
          "right": "assets/Pepete/9s R.webp",
          "rightVideo": false
        },
        {
          "type": "pair",
          "left": "assets/Pepete/10s L.webp",
          "leftVideo": false,
          "right": "assets/Pepete/10s R.webp",
          "rightVideo": false
        },
        {
          "type": "large",
          "src": "assets/Pepete/11L.webp",
          "video": false
        },
        {
          "type": "large",
          "src": "assets/Pepete/12L.webp",
          "video": false
        },
        {
          "type": "pair",
          "left": "assets/Pepete/13s L.webp",
          "leftVideo": false,
          "right": "assets/Pepete/13s R.webp",
          "rightVideo": false
        },
        {
          "type": "large",
          "src": "assets/Pepete/14L.webp",
          "video": false
        },
        {
          "type": "large",
          "src": "assets/Pepete/15L.webp",
          "video": false
        },
        {
          "type": "large",
          "src": "assets/Pepete/16L.webp",
          "video": false
        },
        {
          "type": "large",
          "src": "assets/Pepete/17L.webp",
          "video": false
        }
      ]
    },
    {
      "slug": "urban-oasis",
      "title": "Urban Oasis",
      "description": "Urban Oasis is a concept for a lifestyle brand that merges high tech urban farming with sustainable living products and farming.",
      "direction": [
        "Since Urban Oasis merges technology and ecology, the design language focuses on modern minimalism drawn from natural forms. The logo resembles a U shaped pot holding a pixel style palm tree, referencing the oasis itself. The mark is complex in concept yet simple in execution, which mirrors the brand's overall identity: the mix of simplicity, natural greenery, and neon color rendered in precise pixelated geometry is essentially what the brand is about.",
        "Look closer at the silhouette and there's a smile hidden in the U shaped pot, and open arms formed by the leaves. Both were the original spark, the first idea that came to mind when reading the brief. Everything else in the branding stays deliberately simple. Even the billboard is designed on transparent glass so the trees behind it show through, letting the idea show its work rather than explain itself."
      ],
      "order": 0,
      "cover": {
        "src": "assets/Urban Oasis/1L.webp",
        "video": false
      },
      "gallery": [
        {
          "src": "assets/Urban Oasis/1L.webp",
          "video": false
        },
        {
          "src": "assets/Urban Oasis/2L.webp",
          "video": false
        },
        {
          "src": "assets/Urban Oasis/3L.webp",
          "video": false
        },
        {
          "src": "assets/Urban Oasis/4L.webp",
          "video": false
        },
        {
          "src": "assets/Urban Oasis/5s L.webp",
          "video": false
        },
        {
          "src": "assets/Urban Oasis/5s R.webp",
          "video": false
        },
        {
          "src": "assets/Urban Oasis/6L.webp",
          "video": false
        },
        {
          "src": "assets/Urban Oasis/7s L.webp",
          "video": false
        },
        {
          "src": "assets/Urban Oasis/7s R.webp",
          "video": false
        },
        {
          "src": "assets/Urban Oasis/8L.webp",
          "video": false
        }
      ],
      "rows": [
        {
          "type": "large",
          "src": "assets/Urban Oasis/1L.webp",
          "video": false
        },
        {
          "type": "large",
          "src": "assets/Urban Oasis/2L.webp",
          "video": false
        },
        {
          "type": "large",
          "src": "assets/Urban Oasis/3L.webp",
          "video": false
        },
        {
          "type": "large",
          "src": "assets/Urban Oasis/4L.webp",
          "video": false
        },
        {
          "type": "pair",
          "left": "assets/Urban Oasis/5s L.webp",
          "leftVideo": false,
          "right": "assets/Urban Oasis/5s R.webp",
          "rightVideo": false
        },
        {
          "type": "large",
          "src": "assets/Urban Oasis/6L.webp",
          "video": false
        },
        {
          "type": "pair",
          "left": "assets/Urban Oasis/7s L.webp",
          "leftVideo": false,
          "right": "assets/Urban Oasis/7s R.webp",
          "rightVideo": false
        },
        {
          "type": "large",
          "src": "assets/Urban Oasis/8L.webp",
          "video": false
        }
      ]
    },
    {
      "slug": "",
      "title": "Alwaai Hayat",
      "description": "Alwaai Hayat, literally \"Awareness is Life,\" is a life coaching organization directed at new parents, newly married couples, and individuals who feel lost in life. Its purpose is to guide people through some of life's most disorienting transitions toward a clearer, more grounded sense of self.",
      "direction": [
        "The identity is built with the same intention an NGO would carry: simple, multicolored, and strong. Nothing about it needed to be complicated, the message itself, awareness and renewal, had to come through at a glance.",
        "The logo is a modern depiction of a lotus flower, a symbol that in ancient Egypt represented rebirth and renewal, life beginning again after recreation. Drawn the way it is here, the lotus doubles as a rising sun, a more universal signal for a new day. The open, multi lined leaves carry a second meaning too, they read like open arms, welcoming and reassuring, which is exactly the feeling the brand wants someone to have the moment they consider reaching out for help."
      ],
      "order": 0,
      "cover": {
        "src": "assets/الوعي حياة/1L.webp",
        "video": false
      },
      "gallery": [
        {
          "src": "assets/الوعي حياة/1L.webp",
          "video": false
        },
        {
          "src": "assets/الوعي حياة/2L.webp",
          "video": false
        },
        {
          "src": "assets/الوعي حياة/3s L.webp",
          "video": false
        },
        {
          "src": "assets/الوعي حياة/3s R.webp",
          "video": false
        },
        {
          "src": "assets/الوعي حياة/4s L.webp",
          "video": false
        },
        {
          "src": "assets/الوعي حياة/4s R.webp",
          "video": false
        },
        {
          "src": "assets/الوعي حياة/5L.webp",
          "video": false
        },
        {
          "src": "assets/الوعي حياة/6L.webp",
          "video": false
        },
        {
          "src": "assets/الوعي حياة/7s L.webp",
          "video": false
        },
        {
          "src": "assets/الوعي حياة/7s R.webp",
          "video": false
        },
        {
          "src": "assets/الوعي حياة/8L.webp",
          "video": false
        },
        {
          "src": "assets/الوعي حياة/9L.webp",
          "video": false
        },
        {
          "src": "assets/الوعي حياة/10L.webp",
          "video": false
        },
        {
          "src": "assets/الوعي حياة/11s L.webp",
          "video": false
        },
        {
          "src": "assets/الوعي حياة/11s R.webp",
          "video": false
        }
      ],
      "rows": [
        {
          "type": "large",
          "src": "assets/الوعي حياة/1L.webp",
          "video": false
        },
        {
          "type": "large",
          "src": "assets/الوعي حياة/2L.webp",
          "video": false
        },
        {
          "type": "pair",
          "left": "assets/الوعي حياة/3s L.webp",
          "leftVideo": false,
          "right": "assets/الوعي حياة/3s R.webp",
          "rightVideo": false
        },
        {
          "type": "pair",
          "left": "assets/الوعي حياة/4s L.webp",
          "leftVideo": false,
          "right": "assets/الوعي حياة/4s R.webp",
          "rightVideo": false
        },
        {
          "type": "large",
          "src": "assets/الوعي حياة/5L.webp",
          "video": false
        },
        {
          "type": "large",
          "src": "assets/الوعي حياة/6L.webp",
          "video": false
        },
        {
          "type": "pair",
          "left": "assets/الوعي حياة/7s L.webp",
          "leftVideo": false,
          "right": "assets/الوعي حياة/7s R.webp",
          "rightVideo": false
        },
        {
          "type": "large",
          "src": "assets/الوعي حياة/8L.webp",
          "video": false
        },
        {
          "type": "large",
          "src": "assets/الوعي حياة/9L.webp",
          "video": false
        },
        {
          "type": "large",
          "src": "assets/الوعي حياة/10L.webp",
          "video": false
        },
        {
          "type": "pair",
          "left": "assets/الوعي حياة/11s L.webp",
          "leftVideo": false,
          "right": "assets/الوعي حياة/11s R.webp",
          "rightVideo": false
        }
      ]
    }
  ]
};
